
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Banque", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Banque {


    /**
     * 
     * @return
     *     returns service.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://service/", className = "service.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://service/", className = "service.GetCompteResponse")
    @Action(input = "http://service/Banque/getCompteRequest", output = "http://service/Banque/getCompteResponse")
    public Compte getCompte();

    /**
     * 
     * @param montant
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversionMontant", targetNamespace = "http://service/", className = "service.ConversionMontant")
    @ResponseWrapper(localName = "conversionMontantResponse", targetNamespace = "http://service/", className = "service.ConversionMontantResponse")
    @Action(input = "http://service/Banque/conversionMontantRequest", output = "http://service/Banque/conversionMontantResponse")
    public double conversionMontant(
        @WebParam(name = "montant", targetNamespace = "")
        double montant);

    /**
     * 
     * @return
     *     returns java.util.List<service.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://service/", className = "service.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://service/", className = "service.GetComptesResponse")
    @Action(input = "http://service/Banque/getComptesRequest", output = "http://service/Banque/getComptesResponse")
    public List<Compte> getComptes();

}
